"""опис міграції

Revision ID: 32bdc3fc1e64
Revises: e9f789dc3d7c
Create Date: 2024-07-12 22:51:57.543840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bdc3fc1e64'
down_revision: Union[str, None] = 'e9f789dc3d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
